#---------------------------------------------------#
## 配置文件需要放置在 $HOME/.config/clash/config.yml
##
## 如果您不知道如何操作，请参阅 SS-Rule-Snippet 的 Wiki：
## https://github.com/Hackl0us/SS-Rule-Snippet/wiki/clash(X)
#---------------------------------------------------#

# HTTP 代理端口
port: 1087

# SOCKS5 代理端口
socks-port: 1086

# 允许局域网的连接（可用来共享代理）
allow-lan: false

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: warning

# clash 的 RESTful API
external-controller: 127.0.0.1:9090

dns:
  enable: true
  ipv6: false
  # listen: 0.0.0.0:53
  # enhanced-mode: redir-host # 或 fake-ip
  # # fake-ip-range: 198.18.0.1/16 # 如果你不知道这个参数的作用，请勿修改
  # fake-ip-filter: # fake-ip 白名单列表
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com

  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 114.114.114.114

  fallback: # 与 nameserver 内的服务器列表同时发起请求，当规则符合 GEOIP 在 CN 以外时，fallback 列表内的域名服务器生效。
    - 1.1.1.1
    - 8.8.8.8


Proxy:
# shadowsocks
# 所支持的加密方式与 go-shadowsocks2 保持一致
# 支持加密方式：
#   aes-128-gcm aes-192-gcm aes-256-gcm
#   aes-128-cfb aes-192-cfb aes-256-cfb
#   aes-128-ctr aes-192-ctr aes-256-ctr
#   rc4-md5 chacha20 chacha20-ietf xchacha20
#   chacha20-ietf-poly1305 xchacha20-ietf-poly1305
- { name: "CN2-GIA-1", type: ss, server: <your_server>, port: 27150, cipher: aes-256-gcm, password: <your_password>, udp: true }
- { name: "CN2-GIA-2", type: ss, server: <your_server>, port: 27150, cipher: aes-256-gcm, password: <your_password>, udp: true }
- { name: "CN2-GIA-3", type: ss, server: <your_server>, port: 27150, cipher: aes-256-gcm, password: <your_password>, udp: false, plugin: obfs, plugin-opts: { mode: tls } }
- { name: "CN2-GT-1", type: ss, server: <your_server>, port: 27150, cipher: aes-256-gcm, password: <your_password>, udp: false, plugin: obfs, plugin-opts: { mode: tls } }
- { name: "CN2-GT-2", type: ss, server: <your_server>, port: 27150, cipher: aes-256-cfb, password: <your_password>, udp: true }

Proxy Group:
# select 用来允许用户手动选择 代理服务器 或 服务器组
# 您也可以使用 RESTful API 去切换服务器，这种方式推荐在 GUI 中使用
  - { name: "Proxy", type: select, proxies: ["CN2-GIA-1", "CN2-GIA-2", "CN2-GIA-3", "CN2-GT-1", "CN2-GT-2"] }
  - { name: "UrlTest", type: url-test, proxies: ["CN2-GIA-1", "CN2-GIA-2", "CN2-GIA-3", "CN2-GT-1", "CN2-GT-2"], url: "http://www.gstatic.com/generate_204", interval: 300 }
  - { name: "Apple", type: select, proxies: ["DIRECT", "UrlTest"] }
  - { name: "Netflix", type: select, proxies: ["Proxy"]}

Rule:
    - DOMAIN-SUFFIX, local,          DIRECT
    - IP-CIDR,       127.0.0.1/8,    DIRECT
    - IP-CIDR,       172.16.0.0/12,  DIRECT
    - IP-CIDR,       192.168.0.0/16, DIRECT
    - IP-CIDR,       10.0.0.0/8,     DIRECT
    - IP-CIDR,       17.0.0.0/8,     DIRECT

    # Apple
    - DOMAIN-SUFFIX, apple.com,     Apple
    - DOMAIN-SUFFIX, apple.com.cn,  Apple
    - DOMAIN-SUFFIX, icloud.com,    Apple
    - DOMAIN-SUFFIX, icloud.com.cn, Apple
    - IP-CIDR,       17.0.0.0/8,    Apple

    # Netflix
    - DOMAIN-SUFFIX, fast.com,            Netflix
    - DOMAIN-SUFFIX, netflix.com,         Netflix
    - DOMAIN-SUFFIX, netflix.net,         Netflix
    - DOMAIN-SUFFIX, nflxext.com,         Netflix
    - DOMAIN-SUFFIX, nflximg.com,         Netflix
    - DOMAIN-SUFFIX, nflximg.net,         Netflix
    - DOMAIN-SUFFIX, nflxso.net,          Netflix
    - DOMAIN-SUFFIX, nflxvideo.net,       Netflix
    - DOMAIN-SUFFIX, netflixdnstest0.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest1.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest2.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest3.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest4.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest5.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest6.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest7.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest8.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest9.com, Netflix
    - IP-CIDR,       23.246.0.0/18,       Netflix
    - IP-CIDR,       37.77.184.0/21,      Netflix
    - IP-CIDR,       45.57.0.0/17,        Netflix
    - IP-CIDR,       64.120.128.0/17,     Netflix
    - IP-CIDR,       66.197.128.0/17,     Netflix
    - IP-CIDR,       108.175.32.0/20,     Netflix
    - IP-CIDR,       192.173.64.0/18,     Netflix
    - IP-CIDR,       198.38.96.0/19,      Netflix
    - IP-CIDR,       198.45.48.0/20,      Netflix

    # Microsoft
    - DOMAIN-KEYWORD, onedrive,               DIRECT
    - DOMAIN-SUFFIX,  azure.com,              DIRECT
    - DOMAIN-SUFFIX,  fabric.io,              DIRECT
    - DOMAIN-SUFFIX,  files.1drv.com,         DIRECT
    - DOMAIN-SUFFIX,  hotmail.com,            DIRECT
    - DOMAIN-SUFFIX,  live.com,               DIRECT
    - DOMAIN-SUFFIX,  live.net,               DIRECT
    - DOMAIN-SUFFIX,  livefilestore.com,      DIRECT
    - DOMAIN-SUFFIX,  mesh.com,               DIRECT
    - DOMAIN-SUFFIX,  microsoft.com,          DIRECT
    - DOMAIN-SUFFIX,  microsoftonline.com,    DIRECT
    - DOMAIN-SUFFIX,  microsoft-tst.com,      DIRECT
    - DOMAIN-SUFFIX,  msn.com,                DIRECT
    - DOMAIN-SUFFIX,  office.com,             DIRECT
    - DOMAIN-SUFFIX,  office.net,             DIRECT
    - DOMAIN-SUFFIX,  onedrive.com,           DIRECT
    - DOMAIN-SUFFIX,  outlook.com,            DIRECT
    - DOMAIN-SUFFIX,  p.sfx.ms,               DIRECT
    - DOMAIN-SUFFIX,  sharepoint.com,         DIRECT
    - DOMAIN-SUFFIX,  skype.com,              DIRECT
    - DOMAIN-SUFFIX,  spoprod-a.akamaihd.net, DIRECT
    - DOMAIN-SUFFIX,  storage.msn.com,        DIRECT
    - DOMAIN-SUFFIX,  windows.net,            DIRECT
    - DOMAIN-SUFFIX,  xbox.com,               DIRECT
    - DOMAIN-SUFFIX,  xboxlive.com,           DIRECT

    # Micros
    - DOMAIN-SUFFIX, bitwarden.com, DIRECT
    - DOMAIN-SUFFIX, wiz.money,     DIRECT
    - DOMAIN-SUFFIX, syncbits.com,  DIRECT

    - GEOIP,CN,DIRECT
    - FINAL,UrlTest
