port: 1087
socks-port: 1086

allow-lan: false
external-controller: 127.0.0.1:9090
mode: Rule         # Rule / Global / Direct
log-level: warning # silent / info / warning / error / debug

Proxy:
- { name: "CN2-GIA-1", type: ss, server: <your_server>, port: 27150, cipher: aes-256-gcm, password: <your_password>, udp: true }
- { name: "CN2-GIA-2", type: ss, server: <your_server>, port: 27150, cipher: aes-256-gcm, password: <your_password>, udp: true }
- { name: "CN2-GIA-3", type: ss, server: <your_server>, port: 27150, cipher: aes-256-gcm, password: <your_password>, udp: false, plugin: obfs, plugin-opts: { mode: tls } }
- { name: "CN2-GT-1",  type: ss, server: <your_server>, port: 27150, cipher: aes-256-gcm, password: <your_password>, udp: false, plugin: obfs, plugin-opts: { mode: tls } }
- { name: "CN2-GT-2",  type: ss, server: <your_server>, port: 27150, cipher: aes-256-cfb, password: <your_password>, udp: true }

Proxy Group:
  # type: relay / url-test / fallback / load-balance / select
  - { name: "Proxy",   type: select,   proxies: ["CN2-GIA-1", "CN2-GIA-2", "CN2-GIA-3", "CN2-GT-1", "CN2-GT-2"] }
  - { name: "Auto",    type: url-test, proxies: ["CN2-GIA-1", "CN2-GIA-2", "CN2-GIA-3", "CN2-GT-1", "CN2-GT-2"], url: "http://www.gstatic.com/generate_204", interval: 300 }
  - { name: "Apple",   type: select,   proxies: [ "DIRECT",    "Auto" ] }
  - { name: "Netflix", type: select,   proxies: [ "Proxy" ] }

Rule:
    # Local
    - DOMAIN-SUFFIX, local,          DIRECT
    - DOMAIN-SUFFIX, localhost,      DIRECT
    - IP-CIDR,       127.0.0.0/8,    DIRECT
    - IP-CIDR,       172.16.0.0/12,  DIRECT
    - IP-CIDR,       192.168.0.0/16, DIRECT
    - IP-CIDR,       10.0.0.0/8,     DIRECT
    - IP-CIDR,       17.0.0.0/8,     DIRECT
    - IP-CIDR,       100.64.0.0/10,  DIRECT

    # Apple
    - DOMAIN,        audio-ssl.itunes.apple.com, Apple
    - DOMAIN,        gspe1-ssl.ls.apple.com,     Apple
    - DOMAIN,        itunes.apple.com,           Apple
    - DOMAIN-SUFFIX, aaplimg.com,                Apple
    - DOMAIN-SUFFIX, apple.co,                   Apple
    - DOMAIN-SUFFIX, apple.com,                  Apple
    - DOMAIN-SUFFIX, appstore.com,               Apple
    - DOMAIN-SUFFIX, cdn-apple.com,              Apple
    - DOMAIN-SUFFIX, crashlytics.com,            Apple
    - DOMAIN-SUFFIX, icloud-content.com,         Apple
    - DOMAIN-SUFFIX, icloud.com,                 Apple
    - DOMAIN-SUFFIX, itunes.apple.com,           Apple
    - DOMAIN-SUFFIX, me.com,                     Apple
    - DOMAIN-SUFFIX, mzstatic.com,               Apple

    # Microsoft
    - DOMAIN-SUFFIX, live.com,                              DIRECT
    - DOMAIN-SUFFIX, msocdn.com,                            DIRECT
    - DOMAIN-SUFFIX, office.net,                            DIRECT
    - DOMAIN-SUFFIX, msauth.net,                            DIRECT
    - DOMAIN-SUFFIX, microsoftonline.com,                   DIRECT
    - DOMAIN-SUFFIX, office.com,                            DIRECT
    - DOMAIN-SUFFIX, gfx.ms,                                DIRECT
    - DOMAIN-SUFFIX, microsoft.com,                         DIRECT
    - DOMAIN-SUFFIX, msecnd.net,                            DIRECT
    - DOMAIN-SUFFIX, office365.com,                         DIRECT
    - DOMAIN-SUFFIX, outlook.com,                           DIRECT
    - DOMAIN-SUFFIX, s-microsoft.com,                       DIRECT
    - DOMAIN-SUFFIX, visualstudio.com,                      DIRECT
    - DOMAIN-SUFFIX, windows.com,                           DIRECT
    - DOMAIN-SUFFIX, windowsupdate.com,                     DIRECT
    - DOMAIN,        officecdn-microsoft-com.akamaized.net, DIRECT
    - DOMAIN-SUFFIX, onedrive.live.com,                     DIRECT
    - DOMAIN-SUFFIX, xboxlive.com,                          DIRECT
    - DOMAIN-SUFFIX, 1drv.com,                              DIRECT
    - DOMAIN-SUFFIX, 1drv.ms,                               DIRECT
    - DOMAIN-SUFFIX, blob.core.windows.net,                 DIRECT
    - DOMAIN-SUFFIX, livefilestore.com,                     DIRECT
    - DOMAIN-SUFFIX, onedrive.com,                          DIRECT
    - DOMAIN-SUFFIX, storage.live.com,                      DIRECT
    - DOMAIN-SUFFIX, storage.msn.com,                       DIRECT
    - DOMAIN,        oneclient.sfx.ms,                      DIRECT

    # Netflix
    - DOMAIN-SUFFIX, fast.com,            Netflix
    - DOMAIN-SUFFIX, netflix.com,         Netflix
    - DOMAIN-SUFFIX, netflix.net,         Netflix
    - DOMAIN-SUFFIX, nflxext.com,         Netflix
    - DOMAIN-SUFFIX, nflximg.com,         Netflix
    - DOMAIN-SUFFIX, nflximg.net,         Netflix
    - DOMAIN-SUFFIX, nflxso.net,          Netflix
    - DOMAIN-SUFFIX, nflxvideo.net,       Netflix
    - DOMAIN-SUFFIX, netflixdnstest0.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest1.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest2.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest3.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest4.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest5.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest6.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest7.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest8.com, Netflix
    - DOMAIN-SUFFIX, netflixdnstest9.com, Netflix
    - IP-CIDR,       23.246.0.0/18,       Netflix, no-resolve
    - IP-CIDR,       37.77.184.0/21,      Netflix, no-resolve
    - IP-CIDR,       45.57.0.0/17,        Netflix, no-resolve
    - IP-CIDR,       64.120.128.0/17,     Netflix, no-resolve
    - IP-CIDR,       66.197.128.0/17,     Netflix, no-resolve
    - IP-CIDR,       108.175.32.0/20,     Netflix, no-resolve
    - IP-CIDR,       192.173.64.0/18,     Netflix, no-resolve
    - IP-CIDR,       198.38.96.0/19,      Netflix, no-resolve

    # Twitter
    - DOMAIN-SUFFIX, t.co,        Auto
    - DOMAIN-SUFFIX, twimg.co,    Auto
    - DOMAIN-SUFFIX, twimg.com,   Auto
    - DOMAIN-SUFFIX, twitpic.com, Auto
    - DOMAIN-SUFFIX, twitter.com, Auto

    # Micros
    - DOMAIN-SUFFIX, bitwarden.com, DIRECT
    - DOMAIN-SUFFIX, bitwarden.net, DIRECT
    - DOMAIN-SUFFIX, wiz.money,     DIRECT
    - DOMAIN-SUFFIX, syncbits.com,  DIRECT

    - GEOIP, CN, DIRECT
    - MATCH, Auto
